# pubspec.yaml

name: igenwebapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1 

  cupertino_icons: ^1.0.8
  intl: ^0.20.2 
  
  # === CAMBIO CLAVE: MOVER URL_LAUNCHER AQUI ===
  url_launcher: ^6.3.2 # Usamos la versión más reciente que detectaste

  flutter_hooks: ^0.21.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # url_launcher: ^6.2.2 <--- ELIMINA ESTA LÍNEA

flutter:
  uses-material-design: true

  # Esta sección es necesaria para que Flutter pueda
  # encontrar y cargar los archivos de imagen.
  assets:
    - assets/images/
    - assets/images/logos/ 
    - assets/videos/